export const estadosDict = [
    "AGUASCALIENTES",
    "BAJA CALIFORNIA",
    "BAJA CALIFORNIA SUR",
    "CAMPECHE",
    "CHIAPAS",
    "CHIHUAHUA",
    "COAHUILA DE ZARAGOZA",
    "COLIMA",
    "DURANGO",
    "GUANAJUATO",
    "GUERRERO",
    "HIDALGO",
    "JALISCO",
    "ESTADO DE MEXICO",
    "MICHOACAN DE OCAMPO",
    "MORELOS",
    "NAYARIT",
    "NUEVO LEON",
    "OAXACA",
    "PUEBLA",
    "QUERETARO",
    "QUINTANA ROO",
    "SAN LUIS POTOSI",
    "SINALOA",
    "SONORA",
    "TABASCO",
    "TAMAULIPAS",
    "TLAXCALA",
    "VERACRUZ DE IGNACIO DE LA LLAVE",
    "YUCATAN",
    "ZACATECAS"
];
  

    export const regimenDict = [
    "Régimen General de Ley Personas Morales",
    "Régimen Simplificado de Confianza Personas Morales",
    "Régimen de Incorporación Fiscal",
    "Régimen de Actividades Empresariales y Profesionales",
    "Régimen de Arrendamiento",
    "Régimen de Enajenación o Adquisición de Bienes",
    "Régimen de Dividendos",
    "Régimen de Sociedades Cooperativas de Producción",
    "Régimen de Sociedades Civiles",
    "Régimen de Personas Físicas con Actividades Empresariales",
    "Régimen de Personas Físicas con Actividades Profesionales",
    "Régimen de Personas Físicas con Ingresos por Arrendamiento",
    "Régimen de Personas Físicas con Ingresos por Enajenación de Bienes",
    "Régimen de Personas Físicas con Ingresos por Dividendos",
    "Régimen de Personas Físicas con Ingresos por Sociedades Cooperativas",
    "Régimen de Personas Físicas con Ingresos por Sociedades Civiles"
    ];